# Generated by Django 3.2.8 on 2021-11-01 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoryproductapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='categoryName',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='productCategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='productDescription',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='productName',
        ),
    ]
